export const STATUSES = [
    /* 1xx Informational */
    { code: 100, name: "Continue", title: "請繼續，目前一切正常，伺服器正在等你把話說完", category: "1xx", description: "", asset: "100" },
    { code: 101, name: "Switching Protocols", title:" 協議正在切換中，是時候換個人了", category: "1xx", description: "", asset: "101" },
    { code: 102, name: "Processing", title:" 請稍候!伺服器正在努力處理資訊中(?", category: "1xx", description: "", asset: "102" },
    { code: 103, name: "Early Hints", title:" 先給你一點提示，完整內容等等就來", category: "1xx", description: "", asset: "103" },

    /* 2xx Success */
    { code: 200, name: "OK", category: "2xx", description: "", asset: "" },
    { code: 201, name: "Created", category: "2xx", description: "", asset: "" },
    { code: 202, name: "Accepted", category: "2xx", description: "", asset: "" },
    { code: 203, name: "Non-Authoritative Information", category: "2xx", description: "", asset: "" },
    { code: 204, name: "No Content", category: "2xx", description: "", asset: "" },
    { code: 205, name: "Reset Content", category: "2xx", description: "", asset: "" },
    { code: 206, name: "Partial Content", category: "2xx", description: "", asset: "" },
    { code: 207, name: "Multi-Status", category: "2xx", description: "", asset: "" },
    { code: 208, name: "Already Reported", category: "2xx", description: "", asset: "" },
    { code: 226, name: "IM Used", category: "2xx", description: "", asset: "" },

    /* 3xx Redirection */
    { code: 300, name: "Multiple Choices", category: "3xx", description: "", asset: "" },
    { code: 301, name: "Moved Permanently", category: "3xx", description: "", asset: "" },
    { code: 302, name: "Found", category: "3xx", description: "", asset: "" },
    { code: 303, name: "See Other", category: "3xx", description: "", asset: "" },
    { code: 304, name: "Not Modified", category: "3xx", description: "", asset: "" },
    { code: 305, name: "Use Proxy", category: "3xx", description: "", asset: "" },
    { code: 307, name: "Temporary Redirect", category: "3xx", description: "", asset: "" },
    { code: 308, name: "Permanent Redirect", category: "3xx", description: "", asset: "" },

    /* 4xx Client Error */
    { code: 400, name: "Bad Request", category: "4xx", description: "", asset: "" },
    { code: 401, name: "Unauthorized", category: "4xx", description: "", asset: "" },
    { code: 402, name: "Payment Required", category: "4xx", description: "", asset: "" },
    { code: 403, name: "Forbidden", category: "4xx", description: "", asset: "" },
    { code: 404, name: "Not Found", category: "4xx", description: "", asset: "" },
    { code: 405, name: "Method Not Allowed", category: "4xx", description: "", asset: "" },
    { code: 406, name: "Not Acceptable", category: "4xx", description: "", asset: "" },
    { code: 407, name: "Proxy Authentication Required", category: "4xx", description: "", asset: "" },
    { code: 408, name: "Request Timeout", category: "4xx", description: "", asset: "" },
    { code: 409, name: "Conflict", category: "4xx", description: "", asset: "" },
    { code: 410, name: "Gone", category: "4xx", description: "", asset: "" },
    { code: 411, name: "Length Required", category: "4xx", description: "", asset: "" },
    { code: 412, name: "Precondition Failed", category: "4xx", description: "", asset: "" },
    { code: 413, name: "Payload Too Large", category: "4xx", description: "", asset: "" },
    { code: 414, name: "URI Too Long", category: "4xx", description: "", asset: "" },
    { code: 415, name: "Unsupported Media Type", category: "4xx", description: "", asset: "" },
    { code: 416, name: "Range Not Satisfiable", category: "4xx", description: "", asset: "" },
    { code: 417, name: "Expectation Failed", category: "4xx", description: "", asset: "" },
    { code: 418, name: "I'm a Teapot", category: "4xx", description: "", asset: "" },
    { code: 421, name: "Misdirected Request", category: "4xx", description: "", asset: "" },
    { code: 422, name: "Unprocessable Entity", category: "4xx", description: "", asset: "" },
    { code: 423, name: "Locked", category: "4xx", description: "", asset: "" },
    { code: 424, name: "Failed Dependency", category: "4xx", description: "", asset: "" },
    { code: 425, name: "Too Early", category: "4xx", description: "", asset: "" },
    { code: 426, name: "Upgrade Required", category: "4xx", description: "", asset: "" },
    { code: 428, name: "Precondition Required", category: "4xx", description: "", asset: "" },
    { code: 429, name: "Too Many Requests", category: "4xx", description: "", asset: "" },
    { code: 431, name: "Request Header Fields Too Large", category: "4xx", description: "", asset: "" },
    { code: 451, name: "Unavailable For Legal Reasons", category: "4xx", description: "", asset: "" },

    /* 5xx Server Error */
    { code: 500, name: "Internal Server Error", category: "5xx", description: "", asset: "" },
    { code: 501, name: "Not Implemented", category: "5xx", description: "", asset: "" },
    { code: 502, name: "Bad Gateway", category: "5xx", description: "", asset: "" },
    { code: 503, name: "Service Unavailable", category: "5xx", description: "", asset: "" },
    { code: 504, name: "Gateway Timeout", category: "5xx", description: "", asset: "" },
    { code: 505, name: "HTTP Version Not Supported", category: "5xx", description: "", asset: "" },
    { code: 506, name: "Variant Also Negotiates", category: "5xx", description: "", asset: "" },
    { code: 507, name: "Insufficient Storage", category: "5xx", description: "", asset: "" },
    { code: 508, name: "Loop Detected", category: "5xx", description: "", asset: "" },
    { code: 510, name: "Not Extended", category: "5xx", description: "", asset: "" },
    { code: 511, name: "Network Authentication Required", category: "5xx", description: "", asset: "" }
];