export const STATUSES = [
    /* 1xx Informational */
    { code: 100, title: "Continue", category: "1xx", description: "", asset: "" },
    { code: 101, title: "Switching Protocols", category: "1xx", description: "", asset: "" },
    { code: 102, title: "Processing", category: "1xx", description: "", asset: "" },
    { code: 103, title: "Early Hints", category: "1xx", description: "", asset: "" },

    /* 2xx Success */
    { code: 200, title: "OK", category: "2xx", description: "", asset: "" },
    { code: 201, title: "Created", category: "2xx", description: "", asset: "" },
    { code: 202, title: "Accepted", category: "2xx", description: "", asset: "" },
    { code: 203, title: "Non-Authoritative Information", category: "2xx", description: "", asset: "" },
    { code: 204, title: "No Content", category: "2xx", description: "", asset: "" },
    { code: 205, title: "Reset Content", category: "2xx", description: "", asset: "" },
    { code: 206, title: "Partial Content", category: "2xx", description: "", asset: "" },
    { code: 207, title: "Multi-Status", category: "2xx", description: "", asset: "" },
    { code: 208, title: "Already Reported", category: "2xx", description: "", asset: "" },
    { code: 226, title: "IM Used", category: "2xx", description: "", asset: "" },

    /* 3xx Redirection */
    { code: 300, title: "Multiple Choices", category: "3xx", description: "", asset: "" },
    { code: 301, title: "Moved Permanently", category: "3xx", description: "", asset: "" },
    { code: 302, title: "Found", category: "3xx", description: "", asset: "" },
    { code: 303, title: "See Other", category: "3xx", description: "", asset: "" },
    { code: 304, title: "Not Modified", category: "3xx", description: "", asset: "" },
    { code: 305, title: "Use Proxy", category: "3xx", description: "", asset: "" },
    { code: 307, title: "Temporary Redirect", category: "3xx", description: "", asset: "" },
    { code: 308, title: "Permanent Redirect", category: "3xx", description: "", asset: "" },

    /* 4xx Client Error */
    { code: 400, title: "Bad Request", category: "4xx", description: "", asset: "" },
    { code: 401, title: "Unauthorized", category: "4xx", description: "", asset: "" },
    { code: 402, title: "Payment Required", category: "4xx", description: "", asset: "" },
    { code: 403, title: "Forbidden", category: "4xx", description: "", asset: "" },
    { code: 404, title: "Not Found", category: "4xx", description: "", asset: "" },
    { code: 405, title: "Method Not Allowed", category: "4xx", description: "", asset: "" },
    { code: 406, title: "Not Acceptable", category: "4xx", description: "", asset: "" },
    { code: 407, title: "Proxy Authentication Required", category: "4xx", description: "", asset: "" },
    { code: 408, title: "Request Timeout", category: "4xx", description: "", asset: "" },
    { code: 409, title: "Conflict", category: "4xx", description: "", asset: "" },
    { code: 410, title: "Gone", category: "4xx", description: "", asset: "" },
    { code: 411, title: "Length Required", category: "4xx", description: "", asset: "" },
    { code: 412, title: "Precondition Failed", category: "4xx", description: "", asset: "" },
    { code: 413, title: "Payload Too Large", category: "4xx", description: "", asset: "" },
    { code: 414, title: "URI Too Long", category: "4xx", description: "", asset: "" },
    { code: 415, title: "Unsupported Media Type", category: "4xx", description: "", asset: "" },
    { code: 416, title: "Range Not Satisfiable", category: "4xx", description: "", asset: "" },
    { code: 417, title: "Expectation Failed", category: "4xx", description: "", asset: "" },
    { code: 418, title: "I'm a Teapot", category: "4xx", description: "", asset: "" },
    { code: 421, title: "Misdirected Request", category: "4xx", description: "", asset: "" },
    { code: 422, title: "Unprocessable Entity", category: "4xx", description: "", asset: "" },
    { code: 423, title: "Locked", category: "4xx", description: "", asset: "" },
    { code: 424, title: "Failed Dependency", category: "4xx", description: "", asset: "" },
    { code: 425, title: "Too Early", category: "4xx", description: "", asset: "" },
    { code: 426, title: "Upgrade Required", category: "4xx", description: "", asset: "" },
    { code: 428, title: "Precondition Required", category: "4xx", description: "", asset: "" },
    { code: 429, title: "Too Many Requests", category: "4xx", description: "", asset: "" },
    { code: 431, title: "Request Header Fields Too Large", category: "4xx", description: "", asset: "" },
    { code: 451, title: "Unavailable For Legal Reasons", category: "4xx", description: "", asset: "" },

    /* 5xx Server Error */
    { code: 500, title: "Internal Server Error", category: "5xx", description: "", asset: "" },
    { code: 501, title: "Not Implemented", category: "5xx", description: "", asset: "" },
    { code: 502, title: "Bad Gateway", category: "5xx", description: "", asset: "" },
    { code: 503, title: "Service Unavailable", category: "5xx", description: "", asset: "" },
    { code: 504, title: "Gateway Timeout", category: "5xx", description: "", asset: "" },
    { code: 505, title: "HTTP Version Not Supported", category: "5xx", description: "", asset: "" },
    { code: 506, title: "Variant Also Negotiates", category: "5xx", description: "", asset: "" },
    { code: 507, title: "Insufficient Storage", category: "5xx", description: "", asset: "" },
    { code: 508, title: "Loop Detected", category: "5xx", description: "", asset: "" },
    { code: 510, title: "Not Extended", category: "5xx", description: "", asset: "" },
    { code: 511, title: "Network Authentication Required", category: "5xx", description: "", asset: "" }
];